# Production yaml config
version: "3.8"
services: 
    client:
        build: 
           context: ./client
           dockerfile: Dockerfile.prod
        container_name: mern-client
        ports: 
            - "8080:80"
        depends_on: 
            - server
        networks: 
            - mern-network
    server:
        build: ./server
        container_name: mern-server
        ports: 
            - "5000:5000"
        env_file: ./server/.env.prod
        depends_on: 
            - mongoDB
        networks: 
            - mern-network
    mongoDB:
        image: mongo
        container_name: mongoDB
        ports: 
            - "27017:27017"
        networks: 
            - mern-network
networks: 
    mern-network:
        driver: bridge
