# Development yaml config
version: "3"
services: 
    client:
        build: 
           context: ./client
           dockerfile: Dockerfile.dev
        container_name: mern-client
        volumes:
            - "./client/src:/app/src"
            - "./client/public:/app/public"
        ports: 
            - "3000:3000"
        env_file: .env.client
        environmnet:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        depends_on: 
            - server
        networks: 
            - mern-network
    server:
        build: ./server
        container_name: mern-server
        volumes: 
            - "./server/:/app/server/"
        ports: 
            - "5000:5000"
        env_file: .env.server
        depends_on: 
            - mongodb
        networks: 
            - mern-network
    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes: 
            - data-node:/data/db
        ports: 
            - "27017:27017"
        networks: 
            - mern-network
networks: 
    mern-network:
        driver: bridge
volumes: 
    data-node:
        
